# Configures the Dart analyzer for static code analysis and linting

# Use the recommended Flutter lint rules as base
include: package:flutter_lints/flutter.yaml

linter:
  # Customize lint rules below:
  rules:
    # Uncomment to allow usage of print statements (default: disallow)
    # avoid_print: false

    # Prefer single quotes for strings (uncomment to enable)
    # prefer_single_quotes: true

    # Example additional rules you can enable:
    # prefer_const_constructors: true
    # prefer_final_fields: true
    # unnecessary_this: true

    # Disable a rule example:
    # avoid_returning_null_for_future: false
